# coding: utf-8

"""
    DCV Session Manager

    DCV Session Manager API  # noqa: E501

    OpenAPI spec version: 2020.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateSessionRequestData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'owner': 'str',
        'type': 'str',
        'dcv_gl_enabled': 'bool',
        'max_concurrent_clients': 'int',
        'init_file_path': 'str',
        'permissions_file': 'str',
        'requirements': 'str'
    }

    attribute_map = {
        'name': 'Name',
        'owner': 'Owner',
        'type': 'Type',
        'dcv_gl_enabled': 'DcvGlEnabled',
        'max_concurrent_clients': 'MaxConcurrentClients',
        'init_file_path': 'InitFilePath',
        'permissions_file': 'PermissionsFile',
        'requirements': 'Requirements'
    }

    def __init__(self, name=None, owner=None, type=None, dcv_gl_enabled=None, max_concurrent_clients=None, init_file_path=None, permissions_file=None, requirements=None):  # noqa: E501
        """CreateSessionRequestData - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._owner = None
        self._type = None
        self._dcv_gl_enabled = None
        self._max_concurrent_clients = None
        self._init_file_path = None
        self._permissions_file = None
        self._requirements = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if owner is not None:
            self.owner = owner
        if type is not None:
            self.type = type
        if dcv_gl_enabled is not None:
            self.dcv_gl_enabled = dcv_gl_enabled
        if max_concurrent_clients is not None:
            self.max_concurrent_clients = max_concurrent_clients
        if init_file_path is not None:
            self.init_file_path = init_file_path
        if permissions_file is not None:
            self.permissions_file = permissions_file
        if requirements is not None:
            self.requirements = requirements

    @property
    def name(self):
        """Gets the name of this CreateSessionRequestData.  # noqa: E501

        The descriptive name of the session  # noqa: E501

        :return: The name of this CreateSessionRequestData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateSessionRequestData.

        The descriptive name of the session  # noqa: E501

        :param name: The name of this CreateSessionRequestData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def owner(self):
        """Gets the owner of this CreateSessionRequestData.  # noqa: E501

        The owner of the session  # noqa: E501

        :return: The owner of this CreateSessionRequestData.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this CreateSessionRequestData.

        The owner of the session  # noqa: E501

        :param owner: The owner of this CreateSessionRequestData.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def type(self):
        """Gets the type of this CreateSessionRequestData.  # noqa: E501

        The session type (Virtual or Console)  # noqa: E501

        :return: The type of this CreateSessionRequestData.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CreateSessionRequestData.

        The session type (Virtual or Console)  # noqa: E501

        :param type: The type of this CreateSessionRequestData.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def dcv_gl_enabled(self):
        """Gets the dcv_gl_enabled of this CreateSessionRequestData.  # noqa: E501

        The property that specifies if DcvGl is enabled  # noqa: E501

        :return: The dcv_gl_enabled of this CreateSessionRequestData.  # noqa: E501
        :rtype: bool
        """
        return self._dcv_gl_enabled

    @dcv_gl_enabled.setter
    def dcv_gl_enabled(self, dcv_gl_enabled):
        """Sets the dcv_gl_enabled of this CreateSessionRequestData.

        The property that specifies if DcvGl is enabled  # noqa: E501

        :param dcv_gl_enabled: The dcv_gl_enabled of this CreateSessionRequestData.  # noqa: E501
        :type: bool
        """

        self._dcv_gl_enabled = dcv_gl_enabled

    @property
    def max_concurrent_clients(self):
        """Gets the max_concurrent_clients of this CreateSessionRequestData.  # noqa: E501

        The number of max concurrent clients that can log to a session  # noqa: E501

        :return: The max_concurrent_clients of this CreateSessionRequestData.  # noqa: E501
        :rtype: int
        """
        return self._max_concurrent_clients

    @max_concurrent_clients.setter
    def max_concurrent_clients(self, max_concurrent_clients):
        """Sets the max_concurrent_clients of this CreateSessionRequestData.

        The number of max concurrent clients that can log to a session  # noqa: E501

        :param max_concurrent_clients: The max_concurrent_clients of this CreateSessionRequestData.  # noqa: E501
        :type: int
        """

        self._max_concurrent_clients = max_concurrent_clients

    @property
    def init_file_path(self):
        """Gets the init_file_path of this CreateSessionRequestData.  # noqa: E501

        The init file path on the dcv host  # noqa: E501

        :return: The init_file_path of this CreateSessionRequestData.  # noqa: E501
        :rtype: str
        """
        return self._init_file_path

    @init_file_path.setter
    def init_file_path(self, init_file_path):
        """Sets the init_file_path of this CreateSessionRequestData.

        The init file path on the dcv host  # noqa: E501

        :param init_file_path: The init_file_path of this CreateSessionRequestData.  # noqa: E501
        :type: str
        """

        self._init_file_path = init_file_path

    @property
    def permissions_file(self):
        """Gets the permissions_file of this CreateSessionRequestData.  # noqa: E501

        The permissions file  # noqa: E501

        :return: The permissions_file of this CreateSessionRequestData.  # noqa: E501
        :rtype: str
        """
        return self._permissions_file

    @permissions_file.setter
    def permissions_file(self, permissions_file):
        """Sets the permissions_file of this CreateSessionRequestData.

        The permissions file  # noqa: E501

        :param permissions_file: The permissions_file of this CreateSessionRequestData.  # noqa: E501
        :type: str
        """

        self._permissions_file = permissions_file

    @property
    def requirements(self):
        """Gets the requirements of this CreateSessionRequestData.  # noqa: E501

        The required tags for the session. Example: ram_gb = '4' and software='my software'. The escape char is ', example irish_name='o''neil'   # noqa: E501

        :return: The requirements of this CreateSessionRequestData.  # noqa: E501
        :rtype: str
        """
        return self._requirements

    @requirements.setter
    def requirements(self, requirements):
        """Sets the requirements of this CreateSessionRequestData.

        The required tags for the session. Example: ram_gb = '4' and software='my software'. The escape char is ', example irish_name='o''neil'   # noqa: E501

        :param requirements: The requirements of this CreateSessionRequestData.  # noqa: E501
        :type: str
        """

        self._requirements = requirements

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateSessionRequestData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateSessionRequestData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
