# coding: utf-8

"""
    DCV Session Manager

    DCV Session Manager API  # noqa: E501

    OpenAPI spec version: 2020.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Server(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip': 'str',
        'hostname': 'str',
        'port': 'str',
        'web_url_path': 'str',
        'tags': 'list[KeyValuePair]'
    }

    attribute_map = {
        'ip': 'Ip',
        'hostname': 'Hostname',
        'port': 'Port',
        'web_url_path': 'WebUrlPath',
        'tags': 'Tags'
    }

    def __init__(self, ip=None, hostname=None, port=None, web_url_path=None, tags=None):  # noqa: E501
        """Server - a model defined in Swagger"""  # noqa: E501
        self._ip = None
        self._hostname = None
        self._port = None
        self._web_url_path = None
        self._tags = None
        self.discriminator = None
        if ip is not None:
            self.ip = ip
        if hostname is not None:
            self.hostname = hostname
        if port is not None:
            self.port = port
        if web_url_path is not None:
            self.web_url_path = web_url_path
        if tags is not None:
            self.tags = tags

    @property
    def ip(self):
        """Gets the ip of this Server.  # noqa: E501

        The ip of the server  # noqa: E501

        :return: The ip of this Server.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this Server.

        The ip of the server  # noqa: E501

        :param ip: The ip of this Server.  # noqa: E501
        :type: str
        """

        self._ip = ip

    @property
    def hostname(self):
        """Gets the hostname of this Server.  # noqa: E501

        The hostname of the server  # noqa: E501

        :return: The hostname of this Server.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this Server.

        The hostname of the server  # noqa: E501

        :param hostname: The hostname of this Server.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def port(self):
        """Gets the port of this Server.  # noqa: E501

        The port where the server listens  # noqa: E501

        :return: The port of this Server.  # noqa: E501
        :rtype: str
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this Server.

        The port where the server listens  # noqa: E501

        :param port: The port of this Server.  # noqa: E501
        :type: str
        """

        self._port = port

    @property
    def web_url_path(self):
        """Gets the web_url_path of this Server.  # noqa: E501

        The server web url path  # noqa: E501

        :return: The web_url_path of this Server.  # noqa: E501
        :rtype: str
        """
        return self._web_url_path

    @web_url_path.setter
    def web_url_path(self, web_url_path):
        """Sets the web_url_path of this Server.

        The server web url path  # noqa: E501

        :param web_url_path: The web_url_path of this Server.  # noqa: E501
        :type: str
        """

        self._web_url_path = web_url_path

    @property
    def tags(self):
        """Gets the tags of this Server.  # noqa: E501

        The tags of the server  # noqa: E501

        :return: The tags of this Server.  # noqa: E501
        :rtype: list[KeyValuePair]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Server.

        The tags of the server  # noqa: E501

        :param tags: The tags of this Server.  # noqa: E501
        :type: list[KeyValuePair]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Server, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Server):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
